<?php
function mymodule_menu() {
    $items = array();


    $items['my_module/hello_world'] = array(
        'title' => 'Hello World Test',
        'page callback' => 'say_hello_world',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );


    return $items;
}

function mymodule_js_alter(&$javascript) {
    global $user;
    global $base_url;
    global $databases;
    // print '<pre>';
    // print_r($javascript);
    // exit();
    $mymodule_settings = array(
        'test' => 'this is a setting test',
        'user' => $user,
        'base_url' => $base_url,
        'database' => $databases
    );
    drupal_add_js(array('mymodule' => $mymodule_settings), 'setting');
}


function say_hello_world() {
    $vars = array();
    $vars['type']="ul";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="<div class='my-module'><h2>THIS IS OUR TEST FOR ACQUIA</h2></div>";


    return theme_item_list($vars);
}